replicaCount: 6
image:
  tag: 21
namespace: app
name: springboot-k8-prod
service:
  type: LoadBalancer
  port: 8080

ingressDev:
  enabled: false
ingressProd:
  enabled: false
ingress:
  version: networking.k8s.io/v1-prod

containers:
  resources:
    requests:
      cpu: "250m"
      memory: "200Mi"
    limits:
      cpu: "250m"
      memory: "500Mi"
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 10
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 15