replicaCount: 3

image:
  tag: 22
namespace: app-dev
name: springboot-k8-dev

service:
  type: LoadBalancer
  port: 8080


ingressDev:
  enabled: false
ingressProd:
  enabled: false
ingress:
    version: networking.k8s.io/v1-dev

containers:
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
    readinessProbe:
      httpGet:
        path: /actuator/health
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /actuator/health
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 15