replicaCount: 3

image:
  tag: 21
namespace: app-dev
name: springboot-k8-dev

service:
  type: LoadBalancer
  port: 8080


ingressDev:
  enabled: false
ingressProd:
  enabled: false
ingress:
    version: networking.k8s.io/v1-dev