apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-k8
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: springboot-k8
                port:
                  number: 8080
