apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-k8-dev-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /dev
            pathType: Prefix
            backend:
              service:
                name: springboot-k8-dev
                port:
                  number: 8080