apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-k8-prod-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /prod
            pathType: Prefix
            backend:
              service:
                name: springboot-k8-prod
                port:
                  number: 8080