apiVersion: networking.k8s.io/v2
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
{{/*          - path: /prod*/}}
{{/*            pathType: Prefix*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: {{ .Chart.Name }}-prod*/}}
{{/*                port:*/}}
{{/*                  number: 8080*/}}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-dev
                port:
                  number: 8080
