apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{.Values.namespace }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ .Values.name }}
